Feature/gcd 구현
codesquad-memeber-2020/photos-2 pull request #14
Opened 2020-03-19 12:51 UTC by kjoonk

MenuItem 구현
- FirstResponder
- GestureRecognizer

2020-03-19 13:23 UTC, delmaSong commented
구현사항 
- JSON 데이터 받아오기
- GCD 큐 이용해 비동기적으로 컬렉션셀에 보여주기

2020-03-20 00:54 UTC, delmaSong commented
@godrm 어제 PR 보낼 때, 리뷰어로 등록하는걸 깜빡해서 알림이 안갔나봅니다!

2020-03-20 01:09 UTC, godrm commented
> @godrm 어제 PR 보낼 때, 리뷰어로 등록하는걸 깜빡해서 알림이 안갔나봅니다!

그랬군요 PR을 보기는 했는데, 리뷰어 등록이 안되어 있어서 안봤어요.

2020-03-20 01:29 UTC, godrm requested changes
다음 내용을 확인해보세요.

2020-03-20 01:29 UTC, godrm commented on PhotosApp/PhotosApp/AppDelegate.swift
> +    var navigationController: UINavigationController?
직접 관리하지 않을꺼면 자동으로 처리하도록 두세요. 필요없는 선언 아닐까요?

2020-03-20 01:29 UTC, godrm commented on PhotosApp/PhotosApp/Assets.xcassets/defualtImage.imageset/Contents.json
> +      "scale" : "3x"
이미지 에셋을 활용할 때는 고배율을 사용하세요. 이제 1배율 이미지를 활용하는 디바이스는 없습니다. 
최근 디바이스는 대부분 3배율을 사용합니다.

2020-03-20 01:29 UTC, godrm commented on PhotosApp/PhotosApp/Controller/DoodleViewController.swift
> +private let reuseIdentifier = "doodleViewCell"
클래스 바깥에 선언하는 전역 변수는 지양하세요. 절대금물!
이런 상수를 선언할 때도 어떤 객체와 관련이 있는 것인가 고민해서 포함하도록 선언하세요.

2020-03-20 01:29 UTC, godrm commented on PhotosApp/PhotosApp/Controller/DoodleViewController.swift
> +        }
특정 URL에서 JSON 파일을 다운로드 하는 로직은 뷰 컨트롤러가 처리할 역할이 아닙니다. 
다른 객체로 분리하고 컨트롤러는 지시하도록 상위 모듈로 구현하세요.

2020-03-20 01:29 UTC, godrm commented on PhotosApp/PhotosApp/Controller/DoodleViewController.swift
> +        })
모든 데이터를 가져와야만 콜랙션뷰를 그리는 거라면 100개 아니라 더 많은 10만개이상 되는 앱이면 화면이 안 보이겠네요?
이런 무모한 코드는 좋지 않습니다. 앱 화면은 최대한 빠르게 표시하고, 백그라운드에서 다운로드를 하도록 처리해야 합니다.
그래서 GCD 같은 라이브러리를 활용하는 겁니다.

2020-03-20 01:29 UTC, godrm commented on PhotosApp/PhotosApp/Controller/DoodleViewController.swift
> +    func setImageToCell(cell: UICollectionViewCell, indexPath: IndexPath) {
내부에서 사용하는 메소드라면 private을 명시하세요. 
함수 이름이 여전히 부자연스럽습니다. `cell`도 중복되구요. 
set- check- 이런 추상적인 단어보다 좀 더 구체적인 동작을 표현해도 좋습니다.

2020-03-20 01:29 UTC, godrm commented on PhotosApp/PhotosApp/Controller/DoodleViewController.swift
> +            self.setImageToCell(cell: cell, indexPath: indexPath)
조금 큰 범위를 main 큐에서 처리하는 것 같습니다. 실제로 UIKit 뷰에 접근하는 부분만 비동기로 하는게 어떨까요? 
`collectionView(_:, cellForItemAt:)` 에서 비동기로 처리하는 경우는 조심해야 합니다. 
왜냐하면 셀은 재사용하기 때문에 스크롤을 하면 반복해서 불립니다. 같은 셀에 다른 이미지가 보이는 현상은 없나요?

2020-03-20 01:29 UTC, godrm commented on PhotosApp/PhotosApp/Controller/ViewController.swift
> +        present(navigationController, animated: true, completion: nil)
아닙니다. ViewController가 내비게이션 컨트롤러에 포함되어 있으면, 그대로 표시하면 됩니다. 새롭게 내비게이션 컨트롤러를 포함시킬 필요가 없습니다.

2020-03-20 01:29 UTC, godrm commented on PhotosApp/PhotosApp/Controller/ViewController.swift
> +        cell.becomeFirstResponder()
사진 저장하는 메뉴가 DoodleViewController에 있어야 하지 않나요? 여기는 이미 사진첩에 있는 이미지일텐데요?

2020-03-20 01:29 UTC, godrm commented on PhotosApp/PhotosApp/Model/ImageRequestManager.swift
> +
네트워크 요청하는 부분을 일반화하려고 한 것은 좋은 시도입니다.
- 그럴려면 핸들러 기능이 부족한 것 같습니다. error 나 실패했을 때도 흐름제어가 꼭 되어야 합니다. 
- 일반화시키려했지만 데이터 요청만 하는게 아니라, JSON 분석도 하고, 이미지를 뽑아서 다운로드도 하고 너무 많은 일을 합니다.
- try-catch 부분에서 정상 흐름과 예외 흐름을 꼭 분리하세요. 앞으로는 print()를 하지말고 흐름제어 코드를 꼭 넣으세요. 사용자에게 전달되어야 할지도 고려해보세요.

2020-03-20 01:29 UTC, godrm commented on PhotosApp/PhotosApp/View/DoodleViewCell.swift
> +                self.imageView2.image = image
imageView2 이름을 타입 이름을 쓰지말고 역할을 넣으세요.

2020-03-20 07:04 UTC, merged